### ISSUE TITLE
Can you please review the notification sections from Travis and AppVeyor config files

### ISSUE THREAD

**Issue by gep13** [tapika/swupd#2]
Leaving these as they currently are is causing notifications to be sent to our email address when you run builds.

Specifically, I am requesting that this lines be removed:

https://github.com/tapika/swupd/blob/c1ffde1c9249668a1a08e4ba3d9a7df2e52d2598/.travis.yml#L12-L20

https://github.com/tapika/swupd/blob/c1ffde1c9249668a1a08e4ba3d9a7df2e52d2598/appveyor.yml#L29-L41

**Comment by tapika** [comment]
Hopefully fixed right now.

**Comment by gep13** [comment]
Thank you for fixing that up!
